package com.itecheasy.webservice.oa;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ProfileService service = new ProfileService();
 * ProfileServiceSoap portType = service.getProfileServiceSoap();
 * portType.authorizationLogin(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ProfileService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://oa.itecheasy.com/profileservice.asmx?WSDL")
public class ProfileService extends Service {

//	private final static URL PROFILESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
	.getLogger(com.itecheasy.webservice.oa.ProfileService.class
			.getName());

	private static URL getUrl() {
	URL url = null;
	try {
		URL baseUrl;
		baseUrl = com.itecheasy.webservice.oa.ProfileService.class.getResource(".");
		url = new URL(baseUrl,com.itecheasy.common.util.DeployProperties.getInstance().getOAURL());
	} catch (MalformedURLException e) {
		logger.warning("Failed to create URL for the wsdl Location: '"+com.itecheasy.common.util.DeployProperties.getInstance().getOAURL()+"', retrying as a local file");
		logger.warning(e.getMessage());
	}
	return url;
	}
	
	public ProfileService(URL wsdlLocation, QName serviceName) {
	super(wsdlLocation, serviceName);
	}
	
	public ProfileService() {
	super(getUrl(), new QName("http://tempuri.org/",
			"ProfileService"));
	}

	/**
	 * 
	 * @return returns ProfileServiceSoap
	 */
	@WebEndpoint(name = "ProfileServiceSoap")
	public ProfileServiceSoap getProfileServiceSoap() {
		return super.getPort(new QName("http://tempuri.org/",
				"ProfileServiceSoap"), ProfileServiceSoap.class);
	}

	/**
	 * 
	 * @return returns ProfileServiceSoap
	 */
	@WebEndpoint(name = "ProfileServiceSoap12")
	public ProfileServiceSoap getProfileServiceSoap12() {
		return super.getPort(new QName("http://tempuri.org/",
				"ProfileServiceSoap12"), ProfileServiceSoap.class);
	}

}
