package com.itecheasy.webservice.cms.order;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "OsmsCommunicationOrderService", targetNamespace = "http://osms.communication.itecheasy.com/")
public interface OsmsCommunicationOrderService {

	/**
	 * 
	 * @param orderTrackingCodes
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "completeOrderTracking", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.CompleteOrderTracking")
	@ResponseWrapper(localName = "completeOrderTrackingResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.CompleteOrderTrackingResponse")
	public void completeOrderTracking(
			@WebParam(name = "orderTrackingCodes", targetNamespace = "") List<String> orderTrackingCodes)
			throws BussinessException_Exception;

	/**
	 * 
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateOrderDeliveryInfo", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderDeliveryInfo")
	@ResponseWrapper(localName = "updateOrderDeliveryInfoResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderDeliveryInfoResponse")
	public void updateOrderDeliveryInfo(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1,
			@WebParam(name = "arg2", targetNamespace = "") boolean arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3,
			@WebParam(name = "arg4", targetNamespace = "") String arg4);

	/**
	 * 
	 * @param arg0
	 * @return returns com.itecheasy.webservice.cms.order.OrderModifyRecord
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderModifyRecordById", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderModifyRecordById")
	@ResponseWrapper(localName = "getOrderModifyRecordByIdResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderModifyRecordByIdResponse")
	public OrderModifyRecord getOrderModifyRecordById(@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @param arg6
	 */
	@WebMethod
	@RequestWrapper(localName = "replaceOrder", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.ReplaceOrder")
	@ResponseWrapper(localName = "replaceOrderResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.ReplaceOrderResponse")
	public void replaceOrder(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1,
			@WebParam(name = "arg2", targetNamespace = "") int arg2,
			@WebParam(name = "arg3", targetNamespace = "") List<OrderItem> arg3,
			@WebParam(name = "arg4", targetNamespace = "") List<OrderItem> arg4,
			@WebParam(name = "arg5", targetNamespace = "") List<Integer> arg5,
			@WebParam(name = "arg6", targetNamespace = "") String arg6);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "dealOrderReadySellLackLog", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.DealOrderReadySellLackLog")
	@ResponseWrapper(localName = "dealOrderReadySellLackLogResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.DealOrderReadySellLackLogResponse")
	public void dealOrderReadySellLackLog(@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param maxId
	 * @return returns
	 *         java.util.List<com.itecheasy.webservice.cms.order.CommunicationLog
	 *         >
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderApplayOperatorLogById", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderApplayOperatorLogById")
	@ResponseWrapper(localName = "getOrderApplayOperatorLogByIdResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderApplayOperatorLogByIdResponse")
	public List<CommunicationLog> getOrderApplayOperatorLogById(
			@WebParam(name = "maxId", targetNamespace = "") int maxId);

	/**
	 * 
	 * @param maxId
	 * @return returns
	 *         java.util.List<com.itecheasy.webservice.cms.order.OrderModifyRecord
	 *         >
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderModifyRecordOperatorLogById", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderModifyRecordOperatorLogById")
	@ResponseWrapper(localName = "getOrderModifyRecordOperatorLogByIdResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderModifyRecordOperatorLogByIdResponse")
	public List<OrderModifyRecord> getOrderModifyRecordOperatorLogById(
			@WebParam(name = "maxId", targetNamespace = "") int maxId);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "createPendingOrder", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.CreatePendingOrder")
	@ResponseWrapper(localName = "createPendingOrderResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.CreatePendingOrderResponse")
	public void createPendingOrder(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1,
			@WebParam(name = "arg2", targetNamespace = "") Order arg2,
			@WebParam(name = "arg3", targetNamespace = "") List<OrderItem> arg3) throws BussinessException_Exception;

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "addMultiOrderItem", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.AddMultiOrderItem")
	@ResponseWrapper(localName = "addMultiOrderItemResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.AddMultiOrderItemResponse")
	public void addMultiOrderItem(@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") List<OrderItem> arg2);

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "sendReadyOrderItems", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.SendReadyOrderItems")
	@ResponseWrapper(localName = "sendReadyOrderItemsResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.SendReadyOrderItemsResponse")
	public void sendReadyOrderItems(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1,
			@WebParam(name = "arg2", targetNamespace = "") int arg2,
			@WebParam(name = "arg3", targetNamespace = "") List<OrderItem> arg3,
			@WebParam(name = "arg4", targetNamespace = "") List<Integer> arg4,
			@WebParam(name = "arg5", targetNamespace = "") String arg5);

	/**
	 * 
	 * @param attachmentCode
	 * @return returns byte[]
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getAttachmentByCode", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetAttachmentByCode")
	@ResponseWrapper(localName = "getAttachmentByCodeResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetAttachmentByCodeResponse")
	public byte[] getAttachmentByCode(@WebParam(name = "attachmentCode", targetNamespace = "") String attachmentCode);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateMultiOrderItem", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateMultiOrderItem")
	@ResponseWrapper(localName = "updateMultiOrderItemResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateMultiOrderItemResponse")
	public void updateMultiOrderItem(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") List<OrderItem> arg1);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateOrderItemRemark", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderItemRemark")
	@ResponseWrapper(localName = "updateOrderItemRemarkResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderItemRemarkResponse")
	public void updateOrderItemRemark(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "updateOrderGroup", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderGroup")
	@ResponseWrapper(localName = "updateOrderGroupResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderGroupResponse")
	public void updateOrderGroup(@WebParam(name = "arg0", targetNamespace = "") Integer arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2) throws BussinessException_Exception;

	/**
	 * 
	 * @param startTime
	 * @return returns
	 *         java.util.List<com.itecheasy.webservice.cms.order.CommunicationLog
	 *         >
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderTrackingOperatorLog", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderTrackingOperatorLog")
	@ResponseWrapper(localName = "getOrderTrackingOperatorLogResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderTrackingOperatorLogResponse")
	public List<CommunicationLog> getOrderTrackingOperatorLog(
			@WebParam(name = "startTime", targetNamespace = "") String startTime);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "completeOrder", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.CompleteOrder")
	@ResponseWrapper(localName = "completeOrderResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.CompleteOrderResponse")
	public void completeOrder(@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateOrderRemark", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderRemark")
	@ResponseWrapper(localName = "updateOrderRemarkResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderRemarkResponse")
	public void updateOrderRemark(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "applayOrderResend", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.ApplayOrderResend")
	@ResponseWrapper(localName = "applayOrderResendResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.ApplayOrderResendResponse")
	public void applayOrderResend(@WebParam(name = "arg0", targetNamespace = "") List<String> arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2) throws BussinessException_Exception;

	/**
	 * 
	 * @param orderItemId
	 * @return returns
	 *         java.util.List<com.itecheasy.webservice.cms.order.OrderItemRelateBox
	 *         >
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderItemRelateBoxsByOrderItemId", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderItemRelateBoxsByOrderItemId")
	@ResponseWrapper(localName = "getOrderItemRelateBoxsByOrderItemIdResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderItemRelateBoxsByOrderItemIdResponse")
	public List<OrderItemRelateBox> getOrderItemRelateBoxsByOrderItemId(
			@WebParam(name = "orderItemId", targetNamespace = "") int orderItemId);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateOrderCountry", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderCountry")
	@ResponseWrapper(localName = "updateOrderCountryResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderCountryResponse")
	public void updateOrderCountry(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "cancleOrder", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.CancleOrder")
	@ResponseWrapper(localName = "cancleOrderResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.CancleOrderResponse")
	public void cancleOrder(@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "dealOrderModifyRecord", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.DealOrderModifyRecord")
	@ResponseWrapper(localName = "dealOrderModifyRecordResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.DealOrderModifyRecordResponse")
	public void dealOrderModifyRecord(@WebParam(name = "arg0", targetNamespace = "") Integer arg0,
			@WebParam(name = "arg1", targetNamespace = "") Integer arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2) throws BussinessException_Exception;

	/**
	 * 
	 * @param startTime
	 * @return returns
	 *         java.util.List<com.itecheasy.webservice.cms.order.CommunicationLog
	 *         >
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderOperatorLog", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderOperatorLog")
	@ResponseWrapper(localName = "getOrderOperatorLogResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderOperatorLogResponse")
	public List<CommunicationLog> getOrderOperatorLog(
			@WebParam(name = "startTime", targetNamespace = "") String startTime);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "replaceOrderItem", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.ReplaceOrderItem")
	@ResponseWrapper(localName = "replaceOrderItemResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.ReplaceOrderItemResponse")
	public void replaceOrderItem(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1,
			@WebParam(name = "arg2", targetNamespace = "") int arg2,
			@WebParam(name = "arg3", targetNamespace = "") List<OrderItem> arg3);

	/**
	 * 
	 * @param orderTrackingCodes
	 * @param email
	 * @param userCode
	 * @param userName
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "setConsultationUser", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.SetConsultationUser")
	@ResponseWrapper(localName = "setConsultationUserResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.SetConsultationUserResponse")
	public void setConsultationUser(
			@WebParam(name = "orderTrackingCodes", targetNamespace = "") List<String> orderTrackingCodes,
			@WebParam(name = "userCode", targetNamespace = "") String userCode,
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "email", targetNamespace = "") String email) throws BussinessException_Exception;

	/**
	 * 
	 * @param userId
	 * @param orderTracking
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "replyOrderTracking", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.ReplyOrderTracking")
	@ResponseWrapper(localName = "replyOrderTrackingResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.ReplyOrderTrackingResponse")
	public void replyOrderTracking(@WebParam(name = "orderTracking", targetNamespace = "") OrderTracking orderTracking,
			@WebParam(name = "userId", targetNamespace = "") int userId) throws BussinessException_Exception;

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "cancleOrderItem", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.CancleOrderItem")
	@ResponseWrapper(localName = "cancleOrderItemResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.CancleOrderItemResponse")
	public void cancleOrderItem(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1,
			@WebParam(name = "arg2", targetNamespace = "") int arg2);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateOrderHandlerByCustomer", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderHandlerByCustomer")
	@ResponseWrapper(localName = "updateOrderHandlerByCustomerResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderHandlerByCustomerResponse")
	public void updateOrderHandlerByCustomer(@WebParam(name = "arg0", targetNamespace = "") List<Integer> arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param extension
	 * @param attachment
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "addAttachmentFile", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.AddAttachmentFile")
	@ResponseWrapper(localName = "addAttachmentFileResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.AddAttachmentFileResponse")
	public String addAttachmentFile(@WebParam(name = "attachment", targetNamespace = "") byte[] attachment,
			@WebParam(name = "extension", targetNamespace = "") String extension);

	/**
	 * 
	 * @param remark
	 * @param operater
	 * @param code
	 */
	@WebMethod
	@RequestWrapper(localName = "setOrderTrackingRemark", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.SetOrderTrackingRemark")
	@ResponseWrapper(localName = "setOrderTrackingRemarkResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.SetOrderTrackingRemarkResponse")
	public void setOrderTrackingRemark(@WebParam(name = "code", targetNamespace = "") String code,
			@WebParam(name = "operater", targetNamespace = "") Integer operater,
			@WebParam(name = "remark", targetNamespace = "") String remark);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "dealOrderCommunicationLog", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.DealOrderCommunicationLog")
	@ResponseWrapper(localName = "dealOrderCommunicationLogResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.DealOrderCommunicationLogResponse")
	public void dealOrderCommunicationLog(@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "cancleMultiOrderItem", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.CancleMultiOrderItem")
	@ResponseWrapper(localName = "cancleMultiOrderItemResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.CancleMultiOrderItemResponse")
	public void cancleMultiOrderItem(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1,
			@WebParam(name = "arg2", targetNamespace = "") List<Integer> arg2,
			@WebParam(name = "arg3", targetNamespace = "") List<Integer> arg3);

	/**
	 * 
	 * @param email
	 * @param userCode
	 * @param orderTracking
	 * @param userName
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "setOrderTracking", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.SetOrderTracking")
	@ResponseWrapper(localName = "setOrderTrackingResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.SetOrderTrackingResponse")
	public void setOrderTracking(@WebParam(name = "orderTracking", targetNamespace = "") OrderTracking orderTracking,
			@WebParam(name = "userCode", targetNamespace = "") String userCode,
			@WebParam(name = "userName", targetNamespace = "") String userName,
			@WebParam(name = "email", targetNamespace = "") String email) throws BussinessException_Exception;

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "dealOrderCommunicationLogSuccess", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.DealOrderCommunicationLogSuccess")
	@ResponseWrapper(localName = "dealOrderCommunicationLogSuccessResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.DealOrderCommunicationLogSuccessResponse")
	public void dealOrderCommunicationLogSuccess(@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "requestCollateOrder", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.RequestCollateOrder")
	@ResponseWrapper(localName = "requestCollateOrderResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.RequestCollateOrderResponse")
	public void requestCollateOrder(@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @param arg11
	 * @param arg10
	 * @param arg6
	 * @param arg7
	 * @param arg8
	 * @param arg9
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "updateOrder", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrder")
	@ResponseWrapper(localName = "updateOrderResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderResponse")
	public void updateOrder(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1,
			@WebParam(name = "arg2", targetNamespace = "") int arg2,
			@WebParam(name = "arg3", targetNamespace = "") boolean arg3,
			@WebParam(name = "arg4", targetNamespace = "") int arg4,
			@WebParam(name = "arg5", targetNamespace = "") String arg5,
			@WebParam(name = "arg6", targetNamespace = "") boolean arg6,
			@WebParam(name = "arg7", targetNamespace = "") String arg7,
			@WebParam(name = "arg8", targetNamespace = "") String arg8,
			@WebParam(name = "arg9", targetNamespace = "") String arg9,
			@WebParam(name = "arg10", targetNamespace = "") Boolean arg10,
			@WebParam(name = "arg11", targetNamespace = "") String arg11) throws BussinessException_Exception;

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateOrderHandlerCode", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderHandlerCode")
	@ResponseWrapper(localName = "updateOrderHandlerCodeResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderHandlerCodeResponse")
	public void updateOrderHandlerCode(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param orderTrackingId
	 * @return returns com.itecheasy.webservice.cms.order.OrderTracking
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderTrackingById", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderTrackingById")
	@ResponseWrapper(localName = "getOrderTrackingByIdResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderTrackingByIdResponse")
	public OrderTracking getOrderTrackingById(
			@WebParam(name = "orderTrackingId", targetNamespace = "") int orderTrackingId);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateMutilOrderItemRemark", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateMutilOrderItemRemark")
	@ResponseWrapper(localName = "updateMutilOrderItemRemarkResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateMutilOrderItemRemarkResponse")
	public void updateMutilOrderItemRemark(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") List<OrderItem> arg1);

	/**
	 * 
	 * @return returns
	 *         java.util.List<com.itecheasy.webservice.cms.order.OrderReadySellLackLog
	 *         >
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderReadySellLackLog", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderReadySellLackLog")
	@ResponseWrapper(localName = "getOrderReadySellLackLogResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderReadySellLackLogResponse")
	public List<OrderReadySellLackLog> getOrderReadySellLackLog();

	/**
	 * 
	 * @param startTime
	 * @return returns
	 *         java.util.List<com.itecheasy.webservice.cms.order.OrderModifyRecord
	 *         >
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderModifyRecordOperatorLog", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderModifyRecordOperatorLog")
	@ResponseWrapper(localName = "getOrderModifyRecordOperatorLogResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderModifyRecordOperatorLogResponse")
	public List<OrderModifyRecord> getOrderModifyRecordOperatorLog(
			@WebParam(name = "startTime", targetNamespace = "") String startTime);

	/**
	 * 
	 * @param orderCode
	 * @return returns com.itecheasy.webservice.cms.order.Order
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderByCode", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderByCode")
	@ResponseWrapper(localName = "getOrderByCodeResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderByCodeResponse")
	public Order getOrderByCode(@WebParam(name = "orderCode", targetNamespace = "") String orderCode);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getDeliveryLimiteInfo", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetDeliveryLimiteInfo")
	@ResponseWrapper(localName = "getDeliveryLimiteInfoResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetDeliveryLimiteInfoResponse")
	public String getDeliveryLimiteInfo(@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1,
			@WebParam(name = "arg2", targetNamespace = "") List<Integer> arg2);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateOrderItem", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderItem")
	@ResponseWrapper(localName = "updateOrderItemResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderItemResponse")
	public void updateOrderItem(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") OrderItem arg1);

	/**
	 * 
	 * @param orderTrackingId
	 * @return returns java.util.List<com.itecheasy.webservice.cms.order.
	 *         OrderTrackingReplayHistoryVO>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderTrackingReplayHistory", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderTrackingReplayHistory")
	@ResponseWrapper(localName = "getOrderTrackingReplayHistoryResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderTrackingReplayHistoryResponse")
	public List<OrderTrackingReplayHistoryVO> getOrderTrackingReplayHistory(
			@WebParam(name = "orderTrackingId", targetNamespace = "") int orderTrackingId);

	/**
	 * 
	 * @param startTime
	 * @return returns
	 *         java.util.List<com.itecheasy.webservice.cms.order.CommunicationLog
	 *         >
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderApplayOperatorLog", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderApplayOperatorLog")
	@ResponseWrapper(localName = "getOrderApplayOperatorLogResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderApplayOperatorLogResponse")
	public List<CommunicationLog> getOrderApplayOperatorLog(
			@WebParam(name = "startTime", targetNamespace = "") String startTime);

	/**
	 * 
	 * @param startTime
	 * @return returns
	 *         java.util.List<com.itecheasy.webservice.cms.order.CommunicationLog
	 *         >
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderItemOperatorLog", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderItemOperatorLog")
	@ResponseWrapper(localName = "getOrderItemOperatorLogResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderItemOperatorLogResponse")
	public List<CommunicationLog> getOrderItemOperatorLog(
			@WebParam(name = "startTime", targetNamespace = "") String startTime);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "addOrderItem", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.AddOrderItem")
	@ResponseWrapper(localName = "addOrderItemResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.AddOrderItemResponse")
	public void addOrderItem(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1,
			@WebParam(name = "arg2", targetNamespace = "") OrderItem arg2);

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "updateOrderDelivery", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderDelivery")
	@ResponseWrapper(localName = "updateOrderDeliveryResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderDeliveryResponse")
	public void updateOrderDelivery(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1,
			@WebParam(name = "arg2", targetNamespace = "") Boolean arg2,
			@WebParam(name = "arg3", targetNamespace = "") String arg3,
			@WebParam(name = "arg4", targetNamespace = "") boolean arg4,
			@WebParam(name = "arg5", targetNamespace = "") BigDecimal arg5) throws BussinessException_Exception;

	/**
	 * 
	 * @param arg0
	 * @return returns
	 *         com.itecheasy.webservice.cms.order.OrderWeighingRecordInfo
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getLastOrderWeighingRecordByOrderCode", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetLastOrderWeighingRecordByOrderCode")
	@ResponseWrapper(localName = "getLastOrderWeighingRecordByOrderCodeResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetLastOrderWeighingRecordByOrderCodeResponse")
	public OrderWeighingRecordInfo getLastOrderWeighingRecordByOrderCode(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "requestProcessingOrderItem", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.RequestProcessingOrderItem")
	@ResponseWrapper(localName = "requestProcessingOrderItemResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.RequestProcessingOrderItemResponse")
	public void requestProcessingOrderItem(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") List<Integer> arg1) throws BussinessException_Exception;

	/**
	 * 
	 * @param maxId
	 * @return returns
	 *         java.util.List<com.itecheasy.webservice.cms.order.CommunicationLog
	 *         >
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderOperatorLogById", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderOperatorLogById")
	@ResponseWrapper(localName = "getOrderOperatorLogByIdResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderOperatorLogByIdResponse")
	public List<CommunicationLog> getOrderOperatorLogById(@WebParam(name = "maxId", targetNamespace = "") int maxId);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "updateIsCanSend", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateIsCanSend")
	@ResponseWrapper(localName = "updateIsCanSendResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateIsCanSendResponse")
	public void updateIsCanSend(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") boolean arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2) throws BussinessException_Exception;

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "addReportOrder", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.AddReportOrder")
	@ResponseWrapper(localName = "addReportOrderResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.AddReportOrderResponse")
	public void addReportOrder(@WebParam(name = "arg0", targetNamespace = "") Order arg0,
			@WebParam(name = "arg1", targetNamespace = "") List<OrderItem> arg1);

	/**
	 * 
	 * @param orderTrackingCodes
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "delOrderTracking", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.DelOrderTracking")
	@ResponseWrapper(localName = "delOrderTrackingResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.DelOrderTrackingResponse")
	public void delOrderTracking(
			@WebParam(name = "orderTrackingCodes", targetNamespace = "") List<String> orderTrackingCodes)
			throws BussinessException_Exception;

	/**
	 * 
	 * @param maxId
	 * @return returns java.util.List<com.itecheasy.webservice.cms.order.
	 *         OrderModifyOperatorLog>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderModifyRecordOperatorLogsById", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderModifyRecordOperatorLogsById")
	@ResponseWrapper(localName = "getOrderModifyRecordOperatorLogsByIdResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderModifyRecordOperatorLogsByIdResponse")
	public List<OrderModifyOperatorLog> getOrderModifyRecordOperatorLogsById(
			@WebParam(name = "maxId", targetNamespace = "") int maxId);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateItemPrice", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateItemPrice")
	@ResponseWrapper(localName = "updateItemPriceResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateItemPriceResponse")
	public void updateItemPrice(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") List<OrderItem> arg1);

	/**
	 * 
	 * @param orderId
	 * @return returns
	 *         java.util.List<com.itecheasy.webservice.cms.order.OrderItemDetail
	 *         >
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderItemByOrderId", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderItemByOrderId")
	@ResponseWrapper(localName = "getOrderItemByOrderIdResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderItemByOrderIdResponse")
	public List<OrderItemDetail> getOrderItemByOrderId(@WebParam(name = "orderId", targetNamespace = "") int orderId);

	/**
	 * 
	 * @param consultationTimeEnd
	 * @param consultationUser
	 * @param consultationTimeBegin
	 * @param orderCode
	 * @param status
	 * @param pageSize
	 * @param currentPage
	 * @param type
	 * @param orderCodes
	 * @param orderTrackingCode
	 * @return returns com.itecheasy.webservice.cms.order.OrderTrackingPageList
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findOrderTracking", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.FindOrderTracking")
	@ResponseWrapper(localName = "findOrderTrackingResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.FindOrderTrackingResponse")
	public OrderTrackingPageList findOrderTracking(@WebParam(name = "pageSize", targetNamespace = "") int pageSize,
			@WebParam(name = "currentPage", targetNamespace = "") int currentPage,
			@WebParam(name = "orderTrackingCode", targetNamespace = "") String orderTrackingCode,
			@WebParam(name = "consultationTimeBegin", targetNamespace = "") String consultationTimeBegin,
			@WebParam(name = "consultationTimeEnd", targetNamespace = "") String consultationTimeEnd,
			@WebParam(name = "status", targetNamespace = "") int status,
			@WebParam(name = "orderCode", targetNamespace = "") String orderCode,
			@WebParam(name = "orderCodes", targetNamespace = "") List<String> orderCodes,
			@WebParam(name = "type", targetNamespace = "") int type,
			@WebParam(name = "consultationUser", targetNamespace = "") String consultationUser);

	/**
	 * 
	 * @param orderItemId
	 * @return returns com.itecheasy.webservice.cms.order.OrderItem
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderItemById", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderItemById")
	@ResponseWrapper(localName = "getOrderItemByIdResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderItemByIdResponse")
	public OrderItem getOrderItemById(@WebParam(name = "orderItemId", targetNamespace = "") int orderItemId);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "completeMultiOrder", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.CompleteMultiOrder")
	@ResponseWrapper(localName = "completeMultiOrderResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.CompleteMultiOrderResponse")
	public void completeMultiOrder(@WebParam(name = "arg0", targetNamespace = "") List<String> arg0);

	/**
	 * 
	 * @param arg5
	 * @param arg4
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @param arg11
	 * @param arg10
	 * @param arg6
	 * @param arg7
	 * @param arg8
	 * @param arg9
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "splitOrder", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.SplitOrder")
	@ResponseWrapper(localName = "splitOrderResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.SplitOrderResponse")
	public void splitOrder(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") Integer arg1,
			@WebParam(name = "arg2", targetNamespace = "") XMLGregorianCalendar arg2,
			@WebParam(name = "arg3", targetNamespace = "") BigDecimal arg3,
			@WebParam(name = "arg4", targetNamespace = "") List<Integer> arg4,
			@WebParam(name = "arg5", targetNamespace = "") String arg5,
			@WebParam(name = "arg6", targetNamespace = "") Integer arg6,
			@WebParam(name = "arg7", targetNamespace = "") List<OrderItem> arg7,
			@WebParam(name = "arg8", targetNamespace = "") Boolean arg8,
			@WebParam(name = "arg9", targetNamespace = "") String arg9,
			@WebParam(name = "arg10", targetNamespace = "") String arg10,
			@WebParam(name = "arg11", targetNamespace = "") Boolean arg11) throws BussinessException_Exception;

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "applayOrderCancle", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.ApplayOrderCancle")
	@ResponseWrapper(localName = "applayOrderCancleResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.ApplayOrderCancleResponse")
	public void applayOrderCancle(@WebParam(name = "arg0", targetNamespace = "") List<String> arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2) throws BussinessException_Exception;

	/**
	 * 
	 * @param startTime
	 * @return returns java.util.List<com.itecheasy.webservice.cms.order.
	 *         OrderModifyOperatorLog>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderModifyRecordOperatorLogs", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderModifyRecordOperatorLogs")
	@ResponseWrapper(localName = "getOrderModifyRecordOperatorLogsResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderModifyRecordOperatorLogsResponse")
	public List<OrderModifyOperatorLog> getOrderModifyRecordOperatorLogs(
			@WebParam(name = "startTime", targetNamespace = "") String startTime);

	/**
	 * 
	 * @param maxId
	 * @return returns
	 *         java.util.List<com.itecheasy.webservice.cms.order.CommunicationLog
	 *         >
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderItemOperatorLogById", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderItemOperatorLogById")
	@ResponseWrapper(localName = "getOrderItemOperatorLogByIdResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderItemOperatorLogByIdResponse")
	public List<CommunicationLog> getOrderItemOperatorLogById(@WebParam(name = "maxId", targetNamespace = "") int maxId);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateOrderDiscount", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderDiscount")
	@ResponseWrapper(localName = "updateOrderDiscountResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderDiscountResponse")
	public void updateOrderDiscount(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") BigDecimal arg1,
			@WebParam(name = "arg2", targetNamespace = "") List<OrderItem> arg2);

	/**
	 * 
	 * @param maxId
	 * @return returns
	 *         java.util.List<com.itecheasy.webservice.cms.order.CommunicationLog
	 *         >
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderTrackingOperatorLogById", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderTrackingOperatorLogById")
	@ResponseWrapper(localName = "getOrderTrackingOperatorLogByIdResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderTrackingOperatorLogByIdResponse")
	public List<CommunicationLog> getOrderTrackingOperatorLogById(
			@WebParam(name = "maxId", targetNamespace = "") int maxId);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "applayOrderShelve", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.ApplayOrderShelve")
	@ResponseWrapper(localName = "applayOrderShelveResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.ApplayOrderShelveResponse")
	public void applayOrderShelve(@WebParam(name = "arg0", targetNamespace = "") List<String> arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2) throws BussinessException_Exception;

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "cancelProcessingOrderItem", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.CancelProcessingOrderItem")
	@ResponseWrapper(localName = "cancelProcessingOrderItemResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.CancelProcessingOrderItemResponse")
	public void cancelProcessingOrderItem(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") List<Integer> arg1) throws BussinessException_Exception;

	/**
	 * 
	 * @param orderId
	 * @return returns com.itecheasy.webservice.cms.order.Order
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderById", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderById")
	@ResponseWrapper(localName = "getOrderByIdResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderByIdResponse")
	public Order getOrderById(@WebParam(name = "orderId", targetNamespace = "") int orderId);

	/**
	 * 
	 * @param arg0
	 * @return returns
	 *         java.util.List<com.itecheasy.webservice.cms.order.OrderCommunicationLog
	 *         >
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderCommunicationLog", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderCommunicationLog")
	@ResponseWrapper(localName = "getOrderCommunicationLogResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderCommunicationLogResponse")
	public List<OrderCommunicationLog> getOrderCommunicationLog(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @throws BussinessException_Exception
	 */
	@WebMethod
	@RequestWrapper(localName = "removeOrderGroup", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.RemoveOrderGroup")
	@ResponseWrapper(localName = "removeOrderGroupResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.RemoveOrderGroupResponse")
	public void removeOrderGroup(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1) throws BussinessException_Exception;

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateOrderItemWeight", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderItemWeight")
	@ResponseWrapper(localName = "updateOrderItemWeightResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderItemWeightResponse")
	public void updateOrderItemWeight(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1,
			@WebParam(name = "arg2", targetNamespace = "") int arg2);

	/**
	 * 
	 * @param applayId
	 * @return returns
	 *         com.itecheasy.webservice.cms.order.OrderCancleResendApplay
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getApplayById", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetApplayById")
	@ResponseWrapper(localName = "getApplayByIdResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetApplayByIdResponse")
	public OrderCancleResendApplay getApplayById(@WebParam(name = "applayId", targetNamespace = "") Integer applayId);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "orderSetQuality", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.OrderSetQuality")
	@ResponseWrapper(localName = "orderSetQualityResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.OrderSetQualityResponse")
	public void orderSetQuality(@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns
	 *         java.util.List<com.itecheasy.webservice.cms.order.OrderModifyRecordItem
	 *         >
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getOrderModifyRecords", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderModifyRecords")
	@ResponseWrapper(localName = "getOrderModifyRecordsResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetOrderModifyRecordsResponse")
	public List<OrderModifyRecordItem> getOrderModifyRecords(@WebParam(name = "arg0", targetNamespace = "") Integer arg0);

	/**
	 * 
	 * @param applayId
	 * @return returns java.util.List<com.itecheasy.webservice.cms.order.
	 *         OrderCancleResendApplayItem>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getApplayItemsByApplayId", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetApplayItemsByApplayId")
	@ResponseWrapper(localName = "getApplayItemsByApplayIdResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.GetApplayItemsByApplayIdResponse")
	public List<OrderCancleResendApplayItem> getApplayItemsByApplayId(
			@WebParam(name = "applayId", targetNamespace = "") Integer applayId);

	/**
	 * 
	 * @param orderCode
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "isAssigningOrder", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.IsAssigningOrder")
	@ResponseWrapper(localName = "isAssigningOrderResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.IsAssigningOrderResponse")
	public boolean isAssigningOrder(@WebParam(name = "orderCode", targetNamespace = "") String orderCode);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateOrderPayStatus", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderPayStatus")
	@ResponseWrapper(localName = "updateOrderPayStatusResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderPayStatusResponse")
	public void updateOrderPayStatus(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateOrderHandler", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderHandler")
	@ResponseWrapper(localName = "updateOrderHandlerResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderHandlerResponse")
	public void updateOrderHandler(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "addOrder", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.AddOrder")
	@ResponseWrapper(localName = "addOrderResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.AddOrderResponse")
	public void addOrder(@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") Order arg1,
			@WebParam(name = "arg2", targetNamespace = "") List<OrderItem> arg2,
			@WebParam(name = "arg3", targetNamespace = "") OrderShippingAddress arg3);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateOrderItemQuantity", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderItemQuantity")
	@ResponseWrapper(localName = "updateOrderItemQuantityResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.UpdateOrderItemQuantityResponse")
	public void updateOrderItemQuantity(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1,
			@WebParam(name = "arg2", targetNamespace = "") int arg2,
			@WebParam(name = "arg3", targetNamespace = "") int arg3);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "sendToCustomer", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.SendToCustomer")
	@ResponseWrapper(localName = "sendToCustomerResponse", targetNamespace = "http://osms.communication.itecheasy.com/", className = "com.itecheasy.webservice.cms.order.SendToCustomerResponse")
	public void sendToCustomer(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
