package com.itecheasy.webservice.oa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ProfileServiceSoap", targetNamespace = "http://tempuri.org/")
public interface ProfileServiceSoap {

	/**
	 * 
	 * @param workNumber
	 * @param passWord
	 * @return returns int
	 */
	@WebMethod(operationName = "AuthorizationLogin", action = "http://tempuri.org/AuthorizationLogin")
	@WebResult(name = "AuthorizationLoginResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "AuthorizationLogin", targetNamespace = "http://tempuri.org/", className = "com.itecheasy.webservice.oa.AuthorizationLogin")
	@ResponseWrapper(localName = "AuthorizationLoginResponse", targetNamespace = "http://tempuri.org/", className = "com.itecheasy.webservice.oa.AuthorizationLoginResponse")
	public int authorizationLogin(
			@WebParam(name = "workNumber", targetNamespace = "http://tempuri.org/") String workNumber,
			@WebParam(name = "passWord", targetNamespace = "http://tempuri.org/") String passWord,
			@WebParam(name = "WebServiceSetting", targetNamespace = "http://tempuri.org/", header = true) com.itecheasy.webservice.oa.WebServiceSetting webServiceSetting);

	/**
	 * 
	 * @return returns
	 *         com.itecheasy.webservice.oa.ArrayOfUserModel
	 */
	@WebMethod(operationName = "GetUserList", action = "http://tempuri.org/GetUserList")
	@WebResult(name = "GetUserListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetUserList", targetNamespace = "http://tempuri.org/", className = "com.itecheasy.webservice.oa.GetUserList")
	@ResponseWrapper(localName = "GetUserListResponse", targetNamespace = "http://tempuri.org/", className = "com.itecheasy.webservice.oa.GetUserListResponse")
	public ArrayOfUserModel getUserList();

	/**
	 * 
	 * @param workNumber
	 * @return returns com.itecheasy.webservice.oa.UserModel
	 */
	@WebMethod(operationName = "GetUserModel", action = "http://tempuri.org/GetUserModel")
	@WebResult(name = "GetUserModelResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetUserModel", targetNamespace = "http://tempuri.org/", className = "com.itecheasy.webservice.oa.GetUserModel")
	@ResponseWrapper(localName = "GetUserModelResponse", targetNamespace = "http://tempuri.org/", className = "com.itecheasy.webservice.oa.GetUserModelResponse")
	public UserModel getUserModel(
			@WebParam(name = "workNumber", targetNamespace = "http://tempuri.org/") String workNumber,
			@WebParam(name = "WebServiceSetting", targetNamespace = "http://tempuri.org/", header = true) com.itecheasy.webservice.oa.WebServiceSetting webServiceSetting);

}
