package com.itecheasy.webservice.crm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ForOtherWebServiceSoap", targetNamespace = "http://tempuri.org/")
public interface ForOtherWebServiceSoap {

	/**
	 * ������ϵͳ���õĶ�������
	 * 
	 * @param isOrderLimitModifyByProductIdResult
	 * @param outputMsg
	 * @param newDeliveryId
	 * @param newCountryId
	 * @param cmsProductIds
	 */
	@WebMethod(operationName = "IsOrderLimitModifyByProductId", action = "http://tempuri.org/IsOrderLimitModifyByProductId")
	@RequestWrapper(localName = "IsOrderLimitModifyByProductId", targetNamespace = "http://tempuri.org/", className = "com.itecheasy.webservice.crm.IsOrderLimitModifyByProductId")
	@ResponseWrapper(localName = "IsOrderLimitModifyByProductIdResponse", targetNamespace = "http://tempuri.org/", className = "com.itecheasy.webservice.crm.IsOrderLimitModifyByProductIdResponse")
	public void isOrderLimitModifyByProductId(
			@WebParam(name = "cmsProductIds", targetNamespace = "http://tempuri.org/") String cmsProductIds,
			@WebParam(name = "newCountryId", targetNamespace = "http://tempuri.org/") int newCountryId,
			@WebParam(name = "newDeliveryId", targetNamespace = "http://tempuri.org/") int newDeliveryId,
			@WebParam(name = "outputMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT) Holder<String> outputMsg,
			@WebParam(name = "IsOrderLimitModifyByProductIdResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT) Holder<Boolean> isOrderLimitModifyByProductIdResult);

	/**
	 * ������ϵͳ���õĶ�������
	 * 
	 * @param crmOrderId
	 * @param outputMsg
	 * @param isOrderLimitModifyByOrderIdResult
	 * @param newDeliveryId
	 * @param newCountryId
	 */
	@WebMethod(operationName = "IsOrderLimitModifyByOrderId", action = "http://tempuri.org/IsOrderLimitModifyByOrderId")
	@RequestWrapper(localName = "IsOrderLimitModifyByOrderId", targetNamespace = "http://tempuri.org/", className = "com.itecheasy.webservice.crm.IsOrderLimitModifyByOrderId")
	@ResponseWrapper(localName = "IsOrderLimitModifyByOrderIdResponse", targetNamespace = "http://tempuri.org/", className = "com.itecheasy.webservice.crm.IsOrderLimitModifyByOrderIdResponse")
	public void isOrderLimitModifyByOrderId(
			@WebParam(name = "CRMOrderId", targetNamespace = "http://tempuri.org/") String crmOrderId,
			@WebParam(name = "newCountryId", targetNamespace = "http://tempuri.org/") int newCountryId,
			@WebParam(name = "newDeliveryId", targetNamespace = "http://tempuri.org/") int newDeliveryId,
			@WebParam(name = "outputMsg", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.INOUT) Holder<String> outputMsg,
			@WebParam(name = "IsOrderLimitModifyByOrderIdResult", targetNamespace = "http://tempuri.org/", mode = WebParam.Mode.OUT) Holder<Boolean> isOrderLimitModifyByOrderIdResult);

	/**
	 * ��ȡͷ�̶�����Ϣ
	 * 
	 * @param startDate
	 * @param endDate
	 * @return returns com.itecheasy.webservice.crm.ArrayOfFirstWayOrderInfo
	 */
	@WebMethod(operationName = "GetFirstWayOrder", action = "http://tempuri.org/GetFirstWayOrder")
	@WebResult(name = "GetFirstWayOrderResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetFirstWayOrder", targetNamespace = "http://tempuri.org/", className = "com.itecheasy.webservice.crm.GetFirstWayOrder")
	@ResponseWrapper(localName = "GetFirstWayOrderResponse", targetNamespace = "http://tempuri.org/", className = "com.itecheasy.webservice.crm.GetFirstWayOrderResponse")
	public ArrayOfFirstWayOrderInfo getFirstWayOrder(
			@WebParam(name = "startDate", targetNamespace = "http://tempuri.org/") String startDate,
			@WebParam(name = "endDate", targetNamespace = "http://tempuri.org/") String endDate);

}
