package com.itecheasy.webservice.cms;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * OsmsCommunicationServiceImplService service = new OsmsCommunicationServiceImplService();
 * OsmsCommunicationService portType = service.getOsmsCommunicationServiceImplPort();
 * portType.getAllCategory(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "OsmsCommunicationServiceImplService", targetNamespace = "http://osms.communication.itecheasy.com/", wsdlLocation = "http://192.168.118.14:8080/cms3/services/OsmsCommunicationServiceWS?wsdl")
public class OsmsCommunicationServiceImplService extends Service {

	private final static URL OSMSCOMMUNICATIONSERVICEIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.itecheasy.webservice.cms.OsmsCommunicationServiceImplService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.itecheasy.webservice.cms.OsmsCommunicationServiceImplService.class.getResource(".");
			url = new URL(baseUrl, "http://192.168.118.14:8080/cms3/services/OsmsCommunicationServiceWS?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.118.14:8080/cms3/services/OsmsCommunicationServiceWS?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		OSMSCOMMUNICATIONSERVICEIMPLSERVICE_WSDL_LOCATION = url;
	}

	public OsmsCommunicationServiceImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public OsmsCommunicationServiceImplService() {
		super(OSMSCOMMUNICATIONSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://osms.communication.itecheasy.com/",
				"OsmsCommunicationServiceImplService"));
	}

	/**
	 * 
	 * @return returns OsmsCommunicationService
	 */
	@WebEndpoint(name = "OsmsCommunicationServiceImplPort")
	public OsmsCommunicationService getOsmsCommunicationServiceImplPort() {
		return super.getPort(new QName("http://osms.communication.itecheasy.com/", "OsmsCommunicationServiceImplPort"),
				OsmsCommunicationService.class);
	}

}
