package com.itecheasy.webservice.cms.order;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * OsmsCommunicationOrderServiceImplService service = new OsmsCommunicationOrderServiceImplService();
 * OsmsCommunicationOrderService portType = service.getOsmsCommunicationOrderServiceImplPort();
 * portType.completeOrderTracking(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "OsmsCommunicationOrderServiceImplService", targetNamespace = "http://osms.communication.itecheasy.com/", wsdlLocation = "http://192.168.111.78:8086/cms3/services/OsmsCommunicationOrderService?wsdl")
public class OsmsCommunicationOrderServiceImplService extends Service {

	private final static URL OSMSCOMMUNICATIONORDERSERVICEIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.itecheasy.webservice.cms.order.OsmsCommunicationOrderServiceImplService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.itecheasy.webservice.cms.order.OsmsCommunicationOrderServiceImplService.class
					.getResource(".");
			url = new URL(baseUrl, "http://192.168.111.78:8086/cms3/services/OsmsCommunicationOrderService?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.111.78:8086/cms3/services/OsmsCommunicationOrderService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		OSMSCOMMUNICATIONORDERSERVICEIMPLSERVICE_WSDL_LOCATION = url;
	}

	public OsmsCommunicationOrderServiceImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public OsmsCommunicationOrderServiceImplService() {
		super(OSMSCOMMUNICATIONORDERSERVICEIMPLSERVICE_WSDL_LOCATION, new QName(
				"http://osms.communication.itecheasy.com/", "OsmsCommunicationOrderServiceImplService"));
	}

	/**
	 * 
	 * @return returns OsmsCommunicationOrderService
	 */
	@WebEndpoint(name = "OsmsCommunicationOrderServiceImplPort")
	public OsmsCommunicationOrderService getOsmsCommunicationOrderServiceImplPort() {
		return super.getPort(new QName("http://osms.communication.itecheasy.com/",
				"OsmsCommunicationOrderServiceImplPort"), OsmsCommunicationOrderService.class);
	}

}
