
package com.itecheasy.webservice.dms;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CamsCommunicationService", targetNamespace = "http://cams.communication.itecheasy.com/")
public interface CamsCommunicationService {


    /**
     * 
     * @param propertyValueId
     * @return
     *     returns com.itecheasy.webservice.dms.PropertyValue
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPropertyValueById", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetPropertyValueById")
    @ResponseWrapper(localName = "getPropertyValueByIdResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetPropertyValueByIdResponse")
    public PropertyValue getPropertyValueById(
        @WebParam(name = "propertyValueId", targetNamespace = "")
        int propertyValueId);

    /**
     * 
     * @param cateId
     * @return
     *     returns java.util.List<com.itecheasy.webservice.dms.Property>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPropertyByCategoryId", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetPropertyByCategoryId")
    @ResponseWrapper(localName = "getPropertyByCategoryIdResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetPropertyByCategoryIdResponse")
    public List<Property> getPropertyByCategoryId(
        @WebParam(name = "cateId", targetNamespace = "")
        int cateId);

    /**
     * 
     * @param productId
     * @return
     *     returns java.util.List<com.itecheasy.webservice.dms.ProductPicture>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductPictureByProduct", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetProductPictureByProduct")
    @ResponseWrapper(localName = "getProductPictureByProductResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetProductPictureByProductResponse")
    public List<ProductPicture> getProductPictureByProduct(
        @WebParam(name = "productId", targetNamespace = "")
        int productId);

    /**
     * 
     * @param cateIds
     * @return
     *     returns java.util.List<com.itecheasy.webservice.dms.Property>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPropertyByCategoryIds", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetPropertyByCategoryIds")
    @ResponseWrapper(localName = "getPropertyByCategoryIdsResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetPropertyByCategoryIdsResponse")
    public List<Property> getPropertyByCategoryIds(
        @WebParam(name = "cateIds", targetNamespace = "")
        List<Integer> cateIds);

    /**
     * 
     * @param code
     * @return
     *     returns com.itecheasy.webservice.dms.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserByCode", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetUserByCode")
    @ResponseWrapper(localName = "getUserByCodeResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetUserByCodeResponse")
    public User getUserByCode(
        @WebParam(name = "code", targetNamespace = "")
        String code);

    /**
     * 
     * @param categoryId
     * @return
     *     returns java.util.List<com.itecheasy.webservice.dms.PhCategorySeries>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCategorySeriesByCategroyId", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetCategorySeriesByCategroyId")
    @ResponseWrapper(localName = "getCategorySeriesByCategroyIdResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetCategorySeriesByCategroyIdResponse")
    public List<PhCategorySeries> getCategorySeriesByCategroyId(
        @WebParam(name = "categoryId", targetNamespace = "")
        int categoryId);

    /**
     * 
     * @param productCodes
     * @return
     *     returns java.util.List<com.itecheasy.webservice.dms.CamsProductDetail>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCamsProductDetailByProductCodes", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetCamsProductDetailByProductCodes")
    @ResponseWrapper(localName = "getCamsProductDetailByProductCodesResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetCamsProductDetailByProductCodesResponse")
    public List<CamsProductDetail> getCamsProductDetailByProductCodes(
        @WebParam(name = "productCodes", targetNamespace = "")
        List<String> productCodes);

    /**
     * 
     * @param productCode
     * @throws BussinessException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "cancelBlockedStock", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.CancelBlockedStock")
    @ResponseWrapper(localName = "cancelBlockedStockResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.CancelBlockedStockResponse")
    public void cancelBlockedStock(
        @WebParam(name = "productCode", targetNamespace = "")
        String productCode)
        throws BussinessException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.itecheasy.webservice.dms.Category>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCategory", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetAllCategory")
    @ResponseWrapper(localName = "getAllCategoryResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetAllCategoryResponse")
    public List<Category> getAllCategory();

    /**
     * 
     * @param productId
     * @return
     *     returns java.util.List<com.itecheasy.webservice.dms.CamsProductSpec>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductSpecByProduct", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetProductSpecByProduct")
    @ResponseWrapper(localName = "getProductSpecByProductResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetProductSpecByProductResponse")
    public List<CamsProductSpec> getProductSpecByProduct(
        @WebParam(name = "productId", targetNamespace = "")
        int productId);

    /**
     * 
     * @param productCode
     * @param qty
     * @throws BussinessException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "blockedStock", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.BlockedStock")
    @ResponseWrapper(localName = "blockedStockResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.BlockedStockResponse")
    public void blockedStock(
        @WebParam(name = "productCode", targetNamespace = "")
        String productCode,
        @WebParam(name = "qty", targetNamespace = "")
        int qty)
        throws BussinessException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.itecheasy.webservice.dms.Property>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProperty", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetAllProperty")
    @ResponseWrapper(localName = "getAllPropertyResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetAllPropertyResponse")
    public List<Property> getAllProperty();

    /**
     * 
     * @param parentId
     * @return
     *     returns java.util.List<com.itecheasy.webservice.dms.Category>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCategoryByParentId", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetCategoryByParentId")
    @ResponseWrapper(localName = "getCategoryByParentIdResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetCategoryByParentIdResponse")
    public List<Category> getCategoryByParentId(
        @WebParam(name = "parentId", targetNamespace = "")
        int parentId);

    /**
     * 
     * @param productCodes
     * @return
     *     returns java.util.List<com.itecheasy.webservice.dms.CamsStorageFreeze>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEbayBlockedStock", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetEbayBlockedStock")
    @ResponseWrapper(localName = "getEbayBlockedStockResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetEbayBlockedStockResponse")
    public List<CamsStorageFreeze> getEbayBlockedStock(
        @WebParam(name = "productCodes", targetNamespace = "")
        List<String> productCodes);

    /**
     * 
     * @param cateId
     * @return
     *     returns com.itecheasy.webservice.dms.Category
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCategoryById", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetCategoryById")
    @ResponseWrapper(localName = "getCategoryByIdResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetCategoryByIdResponse")
    public Category getCategoryById(
        @WebParam(name = "cateId", targetNamespace = "")
        int cateId);

    /**
     * 
     * @param productId
     * @return
     *     returns com.itecheasy.webservice.dms.CamsProductDetail
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCamsProductDetailByProductId", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetCamsProductDetailByProductId")
    @ResponseWrapper(localName = "getCamsProductDetailByProductIdResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetCamsProductDetailByProductIdResponse")
    public CamsProductDetail getCamsProductDetailByProductId(
        @WebParam(name = "productId", targetNamespace = "")
        int productId);

    /**
     * 
     * @param propertyId
     * @return
     *     returns com.itecheasy.webservice.dms.Property
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPropertyById", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetPropertyById")
    @ResponseWrapper(localName = "getPropertyByIdResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetPropertyByIdResponse")
    public Property getPropertyById(
        @WebParam(name = "propertyId", targetNamespace = "")
        int propertyId);

    /**
     * 
     * @param productCode
     * @return
     *     returns com.itecheasy.webservice.dms.CamsProductDetail
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCamsProductDetailByProductCode", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetCamsProductDetailByProductCode")
    @ResponseWrapper(localName = "getCamsProductDetailByProductCodeResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetCamsProductDetailByProductCodeResponse")
    public CamsProductDetail getCamsProductDetailByProductCode(
        @WebParam(name = "productCode", targetNamespace = "")
        String productCode);

    /**
     * 
     * @return
     *     returns java.util.List<com.itecheasy.webservice.dms.Category>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllRootCategory", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetAllRootCategory")
    @ResponseWrapper(localName = "getAllRootCategoryResponse", targetNamespace = "http://cams.communication.itecheasy.com/", className = "com.itecheasy.webservice.dms.GetAllRootCategoryResponse")
    public List<Category> getAllRootCategory();

}
